### ISSUE TITLE
v5.0.0 Breaking changes

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#49]
there are a number of issue rising up when:
- you previously made some customization in the tailor blueprints

there are stored in the `App` folder and are still applied even after updating the theme with latest version.
Would be nice to have a process to clean this up somehow.

like running the child theme seed command should solve any of overrided/added blueprint issue

**Comment by artistro08** [comment]
That's exactly why I incremented a v5.0 release to the theme. So this doesn't happen. 

I'm using the philosophy behind the creators of October CMS. 

5 <- major release (includes breaking changes)
0 <- Minor release (includes minor breaking changes)
0 <- build release (No breaking changes expected)

I should have noted this in my release (And in the documentation), and I apologize. However, there's no upgrade guide out yet.

You could potentially fix this by clearing all the blueprints in that folder (minus the ones you edited) and re-seed the theme. Since the `theme:seed` command is October CMS  related, I don't have control over that command.

**Comment by artistro08** [comment]
Now that I think about it, writing a bash script or artisan command to clean up the files would be beneficial to the theme. 

It would need the following functions:
- detect current directory structure
- compare directory structure to the previous version
- use above data to clear up conflicts 
- add in user blueprints and re-link them. 

I unfortunately am not sure how to go about this tho. If you have any suggestions or pull requests, it would be much appreciated.

**Comment by artistro08** [comment]
Closing as the breaking changes are mentioned in the releases now.
