### ISSUE TITLE
Suggestion header.htm HTML

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#75]
Is there a reason why you don't encapsulate the tag `nav` inside a tag `header`?
I think that would be more accurate for the whole page structure overall.

**Comment by chrisvidal** [comment]
Also it would be great to choose if the navbar is inside a `fluid` or `normal` container

**Comment by artistro08** [comment]
The reason why I don't encapsulate the nav inside a header tag is because it goes against semantic HTML guidelines and it wouldn't be found in accessibility templates easily as the header tag is supposed to summarize the text. 

As for the nav structure, I want to leave this alone as it's easier to override the template than to add a setting for it, further complicating everything. 

The main Idea behind the theme is to be able to style it however you wish based on bootstrap's templates. So adding the fluid navbar seems a bit much to me in this case.

**Comment by artistro08** [comment]
Reference of semantic HTML example: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure#active_learning_exploring_the_code_for_our_example

**Comment by artistro08** [comment]
One last thing I want to note, Adding this to the settings gives these options to the clients as well, and if they don't know what they are doing, they could break how the theme looks across the site. 

With that being said, I've added options to the navbar and footer and locked it behind a switch. Check out v6.3.2 to get those updates

Documentation on this tab can be found here: https://artistro08.gitbook.io/tailor-starter-documentation/settings#global-elements-tab

**Comment by chrisvidal** [comment]
> Reference of semantic HTML example: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure#active_learning_exploring_the_code_for_our_example

got it - quite interesting because most of websites do encapsulate the navbar inside a header tag, especially bootstrap themes and templates.

**Comment by artistro08** [comment]
Yeah I know. I've always questioned it myself too.
