### ISSUE TITLE
Question: override the settings blueprint from a child theme

### ISSUE THREAD

**Issue by chrisvidal** [artistro08/tailor-starter#82]
What is the way to go to override the settings blueprint from a child theme?
Knowing that I need to deploy both themes on a server afterward, so I need to keep the overriding code inside my child theme.

If I edit the settings blueprint from the backend editor and migrate it, it saves it under the App folder but nothing under my child theme.

**Comment by artistro08** [comment]
So the way I would do it is documented here:

https://artistro08.gitbook.io/tailor-starter-documentation/pages/blocks/editing-blocks

Since this is only under the pages area, I'll adjust the docs to include it at the root Level when I have time


Long story short, just create a `seeds` folder and copy the settings there. Then seed your settings on top of the first seeding from the tailor starter theme. 


Let me know if this doesn't make sense

**Comment by artistro08** [comment]
Here's a (slightly) Updated doc page with information on that: https://artistro08.gitbook.io/tailor-starter-documentation/editing-blueprint-files

**Comment by chrisvidal** [comment]
thanks @artistro08 

this is how I did it as well, I was just wondering if we could do it another way.

**Comment by artistro08** [comment]
Unfortunately not. I do wish we could as well
